const data={
    products:[
        {
            _id:'1',
            name: 'Nike Slim Shirt',
            category: 'Shirts',
            image: '/images/p1.jpg',
            price: 120,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'2',
            name: 'Adidas Slim Shirt',
            category: 'Shirts',
            image: '/images/p2.jpg',
            price: 100,
            brand: 'Adidas',
            rating: 4.0,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'3',
            name: 'Lacoste Free Slim Shirt',
            category: 'Shirts',
            image: '/images/p3.jpg',
            price: 120,
            brand: 'Lacoste',
            rating: 4.8,
            numReviews: 11,
            description: 'high quality product',
        },
        {
            _id:'4',
            name: 'Nike Slim Pant',
            category: 'Pants',
            image: '/images/p4.jpg',
            price: 78,
            brand: 'Nike',
            rating: 4.9,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'5',
            name: 'Puma Slim Pant',
            category: 'Pants',
            image: '/images/p5.jpg',
            price: 110,
            brand: 'Nike',
            rating: 3.5,
            numReviews: 22,
            description: 'high quality product',
        },
        {
            _id:'6',
            name: 'Adidas Slim Pant',
            category: 'Pants',
            image: '/images/p6.jpg',
            price: 180,
            brand: 'Adidas',
            rating: 5,
            numReviews: 22,
            description: 'high quality product',
        },
    ],
};
export  default data;